#!/usr/bin/env node
/* =============================================================================
   required_marker_test.js, the save rule is the table, said once
   Run:  node dev/tests/required_marker_test.js
   =============================================================================
   I1, from INPUT_UX_AUDIT §3.4, finished at D48 stage C.

   The original defect: eight fields were rejected when empty, four said so with
   two different inline-styled asterisks, and the other four said nothing, so the
   way to discover them was to press Save and be handed a dialog covering the
   field it was about.

   This guard used to start from those eight `alert(t('alert.validation.*'))`
   calls and work back to the input each one read. That was the right source of
   truth while the rule lived in the handlers. It does not any more: `identity`
   is the only tier that blocks a save, the tier is declared in the table, and
   `requireIdentity(level)` reads it. So the guard starts from the table.

   Starting there immediately found three save paths that validated nothing —
   both section handlers and the dictionary EDIT handler — which the old guard
   could not see, because a check that does not exist writes no alert.

   What is protected now:

     1. every identity field can be reached: it resolves to an id, and that id
        is either generated by renderField or declared as `domId` and present
        in the markup.
     2. every identity field carries a marker, derived for generated levels and
        static in the two modals.
     3. every save path for a level with an identity field calls the gate. A
        level that gains a save handler and not a call is how B-091's family
        comes back.
     4. no field-level validation is left hand-written for a field the table
        already calls identity. Two rules for one question is the defect.
     5. B-099's second mark exists and is a DIFFERENT mark: `core` and empty is
        not the same statement as `identity`.
   ============================================================================= */

const { read, moduleFiles, fnSrc, decomment, locale } = require('./_source.js');
const F = require('../../source/modules/field_spec.js');

let pass = 0, fail = 0;
const check = (ok, label, detail) => {
  if (ok) { pass++; console.log(`  ok   ${label}`); }
  else    { fail++; console.log(`  FAIL ${label}`); if (detail) console.log('       ' + detail); }
};

const html = read('LingCoT.html');
const src  = Object.fromEntries([['LingCoT.html', html], ...moduleFiles()]);
const all  = Object.values(src).join('\n');
const loc  = locale();

/* Levels whose forms renderField draws. The rest are modals or read-only rows. */
const GENERATED = ['document', 'section', 'paragraph', 'sentence', 'dict_entry'];

/* ── 1 · every identity field, from the table ───────────────────────────────*/
const identity = [];
for (const level of Object.keys(F.FIELD_SPEC))
  for (const f of F.fieldsInTier(level, 'identity'))
    identity.push({ level, f, id: F.elementIdFor(level, f) });

check(identity.length >= 7, `the table declares ${identity.length} identity field(s)`,
      'no identity fields found — has the tier been renamed?');

for (const { level, f, id } of identity) {
  /* A readonly control is shown rather than edited: the word and morpheme forms
     come from the parse, and retokenizing is how they change. Nothing to mark
     and nothing to gate. */
  if (f.control === 'readonly') { check(true, `${level}.${f.key} is read-only, correctly not gated`); continue; }

  check(!!id, `${level}.${f.key} resolves to an element id`);
  if (f.domId)
    check(new RegExp(`id="${f.domId}"`).test(all),
          `${level}.${f.key} declares domId ${f.domId}, and the markup has it`,
          'a declared id that does not exist makes the gate silently pass');
  else if (level === 'lemma')
    /* The one level with neither a generated form nor a modal. A lemma is
       created from the quick panel, whose ids are built from the host input's
       id (`${inputId}-ql-lform`) so that the same panel can serve both
       dictionary forms. There is no single id for the table to name, which is
       why this level is reached through its emptyMsg instead — checked above,
       and its gate is checked separately below. */
    check(/id="\$\{inputId\}-ql-lform"/.test(all),
          'lemma.form lives on the quick panel, whose ids derive from its host');
  else
    check(GENERATED.includes(level),
          `${level}.${f.key} is on a generated form, so renderField draws its id`,
          'a level with neither a generated form nor a domId cannot be reached');

  /* Every identity field needs its own words for the one surface that has no
     strip host to put them in. */
  check(!!f.emptyMsg, `${level}.${f.key} declares an emptyMsg`);
  if (f.emptyMsg)
    check(Object.prototype.hasOwnProperty.call(loc, f.emptyMsg),
          `and ${f.emptyMsg} exists in the locale`,
          't() returns the key itself on a miss, so this would be shown raw');
}

/* ── 2 · the marker, derived not hand-placed ────────────────────────────────*/
const rf = fnSrc('LingCoT.html', 'renderField') || '';
check(/f\.tier === 'identity' \? requiredMark\(\)/.test(rf),
      'renderField marks every identity-tier field, which is the whole rule');
check(/f\.tier === 'core' && isEmptyValue\(cur\)\)\s*\?\s*wantedMark\(\)/.test(rf),
      'and marks a core field that is empty, which is B-099',
      'the two marks say different things and both have to be derived');
check(/function wantedMark\(\)/.test(html), 'wantedMark() is defined');
check(!/wantedMark\(\)/.test(rf.replace(/f\.tier === 'core'[\s\S]*?wantedMark\(\)/, '')),
      'the wanted mark is applied in one place only');

/* Hand-written markup keeps a static marker. A `readonly` identity control is
   shown rather than typed into (word.form, morpheme.form), so it has no label to
   bind and nothing to mark: the save cannot refuse a value nobody can enter. */
for (const { f } of identity.filter(x => x.f.domId && x.f.control !== 'readonly')) {
  const label = new RegExp(`<label[^>]*for="${f.domId}"[^>]*>([\\s\\S]{0,220}?)</label>`).exec(all);
  check(!!label, `${f.domId} has a label bound to it`);
  if (label)
    check(/class="required"/.test(label[1]), `${f.domId} is marked required`,
          label[1].trim().slice(0, 80));
}

/* ── 3 · every save path for such a level calls the gate ────────────────────
   Named by level rather than by handler, because the handlers are what keep
   being added. A level with identity fields whose name appears in a save
   function and nowhere in a requireIdentity call is the gap. */
const gated = new Set([...all.matchAll(/requireIdentity\('(\w+)'\)/g)].map(m => m[1]));
for (const level of new Set(identity.filter(x => x.f.control !== 'readonly').map(x => x.level))) {
  /* The lemma level has no form of its own: it is created from the quick panel,
     whose ids are derived from the host input. It is checked below instead. */
  if (level === 'lemma') continue;
  check(gated.has(level), `${level}'s save path calls requireIdentity`,
        'an identity field nothing checks is a field that is not identity');
}
const evt = decomment(src['events.js'] || '');
check(/fieldOf\('lemma', 'form'\)\?\.emptyMsg/.test(evt),
      "the quick-lemma panel takes its message from the table",
      'the one gate that cannot use requireIdentity must still not restate the rule');

/* ── 4 · no second copy of the rule ─────────────────────────────────────────*/
const handRolled = [...decomment(all).matchAll(
  /if \(!\w+(?:\.length)?\)\s*\{?\s*alert\(t\('(alert\.validation\.[a-z_]+)'\)\)/g)].map(m => m[1]);
/* Two survive on purpose and are named, so a third is visible immediately.
   `no_text_lines` asks whether the ingest produced any sentences, which is not
   a field and has no box to point at. `lemma_form_required` is the quick panel,
   reached through the table above. */
const allowed = new Set(['alert.validation.no_text_lines', 'alert.validation.lemma_form_required']);
const strays = handRolled.filter(k => !allowed.has(k));
check(strays.length === 0,
      'no field validation is hand-written for a field the table calls identity',
      strays.join(', ') + ' — use requireIdentity(level)');

/* A message with no call site reads as a rule that exists. tokenizeWords filters
   empty strings, so a word cannot exist without a form: prevented, not checked. */
check(!Object.prototype.hasOwnProperty.call(loc, 'alert.validation.word_form_required'),
      'the word-form message is deleted, not wired up',
      'D48: prevent by construction where you can, and do not keep the message');

/* ── 5 · one marker each, in the stylesheet ─────────────────────────────────*/
const css = read('LingCoT.css');
check(!/<span style="[^"]*var\(--accent\)[^"]*">\*<\/span>/.test(all),
      'no inline-styled asterisk survives');
check(/^\.required\s*\{/m.test(css), '.required is defined in the stylesheet');
check(/^\.wanted\s*\{/m.test(css),   '.wanted is defined in the stylesheet');
check(/^\.req-strip:empty\s*\{[^}]*display:\s*none/m.test(css),
      'an empty verdict host occupies nothing',
      'otherwise every form grows a gap under its first label');

/* ── 6 · the quick-lemma panel, still one ───────────────────────────────────*/
const qlBlocks = [...all.matchAll(/<span class="ql-lbl">([\s\S]{0,160}?)<\/span>\s*<input[^>]*id="([\w${}-]*-ql-lform)"/g)];
check(qlBlocks.length === 1, 'one quick-lemma panel, shared', `got ${qlBlocks.length}`);
for (const b of qlBlocks)
  check(/requiredMark\(\)/.test(b[1]), `${b[2]} is marked required`, b[1].trim().slice(0, 120));

/* ── 7 · the marked words are translatable ──────────────────────────────────*/
check(!/<label[^>]*for="(cn-title|de-title)"[^>]*>Title/.test(all),
      'the title labels are keyed, not hardcoded English');
check(!/<label[^>]*for="(am-name|sm-name)"[^>]*>Name/.test(all),
      'the modal name labels are keyed, not hardcoded English');

console.log(`\n  ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
